//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeStore_Bondarev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Номер_Заказа { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<System.DateTime> Дата_Заказа { get; set; }
        public Nullable<System.DateTime> Дата_Доставки { get; set; }
        public Nullable<int> Адрес_Пункта_Выдачи { get; set; }
        public Nullable<int> Код_Для_Получения { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
        public virtual PickupPoint PickupPoint { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
