//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeStore_Bondarev
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickupPoint
    {
        public PickupPoint()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id_Пункта { get; set; }
        public string Индекс { get; set; }
        public string Город { get; set; }
        public string Улица { get; set; }
        public string Дом { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
