//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeStore_Bondarev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public string Артикул { get; set; }
        public string Наименование_Товара { get; set; }
        public string Единица_Измерения { get; set; }
        public Nullable<decimal> Цена { get; set; }
        public Nullable<int> Id_Поставщика { get; set; }
        public Nullable<int> Id_Производителя { get; set; }
        public Nullable<int> Id_Категории { get; set; }
        public Nullable<int> Действующая_Скидка { get; set; }
        public Nullable<int> Кол_во_На_Складе { get; set; }
        public string Описание_Товара { get; set; }
        public string Фото { get; set; }
    
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
